Repository Level/rocksdb, pull requests merged in 2019-04, with the labels that each got.

#98 Read only support for rocksdb
  src/database.cc
  src/database.h
  src/database_async.cc
  src/database_async.h
  test/open-read-only-test.js
Labels: semver-minor

#102 Remove prebuild script from package.json
  package.json
Labels: cleanup, semver-patch

#101 Update gitignore and npmignore
  .gitignore
  .npmignore
Labels: cleanup, semver-patch

#103 Prepare next
  CHANGELOG.md
  CONTRIBUTORS.md
Labels: documentation
